<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 2019/3/21
 * Time: 下午2:36
 */
namespace anlewo\tabgridview;

use yii\base\Widget;

class TabGridViewWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return 123123123;
    }
}
